// Package intgen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package intgen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorEnvelopeErrorKind.
const (
	BadCapability ErrorEnvelopeErrorKind = "bad_capability"
	BadSpec       ErrorEnvelopeErrorKind = "bad_spec"
	FsError       ErrorEnvelopeErrorKind = "fs_error"
	Internal      ErrorEnvelopeErrorKind = "internal"
	NoCapability  ErrorEnvelopeErrorKind = "no_capability"
	NoSuchPath    ErrorEnvelopeErrorKind = "no_such_path"
	NotFound      ErrorEnvelopeErrorKind = "not_found"
	NotOwner      ErrorEnvelopeErrorKind = "not_owner"
	NotRunning    ErrorEnvelopeErrorKind = "not_running"
	StaleEpoch    ErrorEnvelopeErrorKind = "stale_epoch"
	TooMany       ErrorEnvelopeErrorKind = "too_many"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorKind enum.
func (e ErrorEnvelopeErrorKind) Valid() bool {
	switch e {
	case BadCapability:
		return true
	case BadSpec:
		return true
	case FsError:
		return true
	case Internal:
		return true
	case NoCapability:
		return true
	case NoSuchPath:
		return true
	case NotFound:
		return true
	case NotOwner:
		return true
	case NotRunning:
		return true
	case StaleEpoch:
		return true
	case TooMany:
		return true
	default:
		return false
	}
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Kind    ErrorEnvelopeErrorKind `json:"kind"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorEnvelopeErrorKind defines model for ErrorEnvelope.Error.Kind.
type ErrorEnvelopeErrorKind string

// ExtTree defines model for ExtTree.
type ExtTree struct {
	// Files Slash-relative path to file contents.
	Files map[string][]byte `json:"files"`

	// Sum h1: dirhash of the source tree.
	Sum string `json:"sum"`
}

// Error defines model for Error.
type Error = ErrorEnvelope

// ExtTreeParams defines parameters for ExtTree.
type ExtTreeParams struct {
	// Path Absolute local identifier path to resolve.
	Path string `form:"path" json:"path"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ExtTree (worker → API) Fetch a local extension source tree.
	// (GET /internal/v1/ext/tree)
	ExtTree(c *gin.Context, params ExtTreeParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ExtTree operation middleware
func (siw *ServerInterfaceWrapper) ExtTree(c *gin.Context) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ExtTreeParams

	// ------------- Required query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "path", c.Request.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter path: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExtTree(c, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/internal/v1/ext/tree", wrapper.ExtTree)
}

type ErrorJSONResponse ErrorEnvelope

type ExtTreeRequestObject struct {
	Params ExtTreeParams
}

type ExtTreeResponseObject interface {
	VisitExtTreeResponse(w http.ResponseWriter) error
}

type ExtTree200JSONResponse ExtTree

func (response ExtTree200JSONResponse) VisitExtTreeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ExtTreedefaultJSONResponse struct {
	Body       ErrorEnvelope
	StatusCode int
}

func (response ExtTreedefaultJSONResponse) VisitExtTreeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ExtTree (worker → API) Fetch a local extension source tree.
	// (GET /internal/v1/ext/tree)
	ExtTree(ctx context.Context, request ExtTreeRequestObject) (ExtTreeResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// ExtTree operation middleware
func (sh *strictHandler) ExtTree(ctx *gin.Context, params ExtTreeParams) {
	var request ExtTreeRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ExtTree(ctx, request.(ExtTreeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExtTree")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ExtTreeResponseObject); ok {
		if err := validResponse.VisitExtTreeResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}
