/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["authConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["capabilities"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Session or anonymous (dev) auth only — API keys get 403. */
        get: operations["listKeys"];
        put?: never;
        /** @description Session or anonymous (dev) auth only — API keys get 403. */
        post: operations["createKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** @description Session or anonymous (dev) auth only — API keys get 403. */
        delete: operations["deleteKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInstances"];
        put?: never;
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getInstance"];
        put?: never;
        post?: never;
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/keepalive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["keepalive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["files"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/instances/{id}/executions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExecutions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAudit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPolicies"];
        put?: never;
        post: operations["createPolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["validatePolicy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/policies/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPolicy"];
        put: operations["updatePolicy"];
        post?: never;
        delete: operations["deletePolicy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Session or anonymous (dev) auth only — API keys get 403. Never returns values. */
        get: operations["listSecrets"];
        put?: never;
        /** @description Session or anonymous (dev) auth only — API keys get 403. Value is write-only. */
        post: operations["createSecret"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/secrets/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Session or anonymous (dev) auth only — API keys get 403. */
        put: operations["updateSecret"];
        post?: never;
        /** @description Session or anonymous (dev) auth only — API keys get 403. */
        delete: operations["deleteSecret"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Clear the session cookie (redirects to /login) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Redirect to Google OIDC authorize URL */
        get: operations["googleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC callback; sets cs_session cookie */
        get: operations["googleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        InstanceStatus: "running" | "deleted" | "expired" | "lost";
        /** @enum {string} */
        ExecStatus: "ok" | "error";
        /** @enum {string} */
        ExecErrorType: "syntax" | "runtime" | "policy_denied" | "out_of_scope" | "timeout" | "step_limit" | "memory_limit";
        /** @enum {string} */
        Decision: "allow" | "deny";
        /**
         * @description audit event phase; "" = no phase (runtime error / out of scope)
         * @enum {string}
         */
        Phase: "" | "before" | "after";
        /** @enum {string} */
        CapabilityName: "fs" | "net" | "io";
        /** @enum {string} */
        HTTPMethod: "GET" | "HEAD" | "POST" | "PUT" | "PATCH" | "DELETE" | "OPTIONS";
        /** @enum {string} */
        SecretSource: "vault" | "inline";
        /** @enum {string} */
        APIErrorCode: "auth_failed" | "bad_capability" | "bad_policy" | "bad_request" | "bad_secret" | "bad_spec" | "conflict" | "csrf" | "forbidden" | "fs_error" | "internal" | "method_not_allowed" | "no_fs" | "not_found" | "not_running" | "secrets_disabled" | "too_large" | "too_many" | "unauthorized";
        /** @enum {string} */
        FieldType: "int" | "bool" | "string" | "string_list" | "string_map";
        /** @enum {string} */
        AuthKind: "session" | "api_key" | "anonymous";
        ErrorEnvelope: {
            error: {
                code: components["schemas"]["APIErrorCode"];
                message: string;
            };
        };
        OkResponse: {
            ok?: boolean;
        };
        AuthConfig: {
            google: boolean;
            /** @description dev mode — anonymous login */
            dev_mode: boolean;
            /** @description vault secrets enabled (--secret-key set) */
            secrets: boolean;
        };
        User: {
            id: string;
            email: string;
            name: string;
            google_sub?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_login_at: string;
        };
        MeInfo: {
            user: components["schemas"]["User"];
            via_key: boolean;
            kind: components["schemas"]["AuthKind"];
        };
        OpDoc: {
            name?: string;
            doc?: string;
            params?: string[];
        };
        FieldDoc: {
            name?: string;
            type?: components["schemas"]["FieldType"];
            doc?: string;
            default?: unknown;
        };
        CapabilityDoc: {
            name?: components["schemas"]["CapabilityName"];
            ops?: components["schemas"]["OpDoc"][];
            config_fields?: components["schemas"]["FieldDoc"][];
        };
        CapabilityCatalog: {
            capabilities?: components["schemas"]["CapabilityDoc"][];
        };
        APIKey: {
            id: string;
            user_id: string;
            name: string;
            prefix: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_used_at?: string;
            /** Format: date-time */
            expires_at?: string;
            /** Format: date-time */
            revoked_at?: string;
        };
        CreateKeyRequest: {
            name: string;
            /** Format: int64 */
            expires_in_seconds?: number;
        };
        CreatedKey: {
            key?: components["schemas"]["APIKey"];
            /** @description full API key */
            secret?: string;
        };
        KeysResponse: {
            keys?: components["schemas"]["APIKey"][];
        };
        SecretSpec: {
            /** @description vault secret name (mutually exclusive with value) */
            ref?: string;
            /** @description inline secret value (never persisted) */
            value?: string;
            allowed_domains?: string[];
            source?: components["schemas"]["SecretSource"];
        };
        Limits: {
            /** Format: int64 */
            exec_timeout_ms?: number;
            /** Format: int64 */
            max_steps?: number;
            /** Format: int64 */
            max_output_bytes?: number;
        };
        InstanceSpec: {
            /** Format: int64 */
            ttl_seconds?: number;
            labels?: {
                [key: string]: string;
            };
            env?: {
                [key: string]: string;
            };
            secrets?: {
                [key: string]: components["schemas"]["SecretSpec"];
            };
            capabilities?: {
                [key: string]: unknown;
            };
            limits?: components["schemas"]["Limits"];
        };
        Instance: {
            id: string;
            user_id: string;
            spec: components["schemas"]["InstanceSpec"];
            labels: {
                [key: string]: string;
            };
            status: components["schemas"]["InstanceStatus"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_active_at: string;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            ended_at?: string;
        };
        InstanceResponse: {
            instance?: components["schemas"]["Instance"];
        };
        InstancesResponse: {
            instances?: components["schemas"]["Instance"][];
        };
        ExecRequest: {
            code: string;
            /** Format: int64 */
            timeout_ms?: number;
        };
        ExecError: {
            type: components["schemas"]["ExecErrorType"];
            message: string;
            backtrace?: string;
        };
        ExecResult: {
            exec_id: string;
            output: string;
            error: components["schemas"]["ExecError"];
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            steps: number;
        };
        FileEntry: {
            name: string;
            path: string;
            is_dir: boolean;
            /** Format: int64 */
            size: number;
            /** Format: int64 */
            mtime: number;
        };
        /** @description either a directory listing or a file's path+content */
        FilesResult: {
            entries?: components["schemas"]["FileEntry"][];
            path?: string;
            content?: string;
        };
        Execution: {
            id: string;
            instance_id: string;
            user_id: string;
            code_sha256: string;
            code_snippet: string;
            status: components["schemas"]["ExecStatus"];
            error_type?: components["schemas"]["ExecErrorType"];
            /** Format: int64 */
            duration_ms: number;
            /** Format: int64 */
            steps: number;
            /** Format: int64 */
            output_bytes: number;
            /** Format: date-time */
            created_at: string;
        };
        ExecutionsResponse: {
            executions?: components["schemas"]["Execution"][];
        };
        AuditEvent: {
            id: string;
            /** Format: date-time */
            ts: string;
            user_id: string;
            instance_id: string;
            exec_id: string;
            capability: components["schemas"]["CapabilityName"];
            op: string;
            /** @description JSON */
            args: string;
            phase: components["schemas"]["Phase"];
            decision: components["schemas"]["Decision"];
            reason: string;
            error: string;
            /** Format: int64 */
            duration_ms: number;
        };
        AuditResponse: {
            events?: components["schemas"]["AuditEvent"][];
        };
        Policy: {
            id: string;
            user_id: string;
            name: string;
            rego: string;
            enabled: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        PolicyRequest: {
            name: string;
            rego: string;
            enabled?: boolean;
        };
        PolicyUpdateRequest: {
            name?: string;
            rego?: string;
            enabled?: boolean;
        };
        PolicyResponse: {
            policy?: components["schemas"]["Policy"];
        };
        PoliciesResponse: {
            policies?: components["schemas"]["Policy"][];
        };
        ValidatePolicyRequest: {
            rego: string;
        };
        ValidationResult: {
            valid: boolean;
            error?: string;
        };
        Secret: {
            id: string;
            user_id: string;
            name: string;
            allowed_domains: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateSecretRequest: {
            name: string;
            /** @description write-only; never returned */
            value: string;
            allowed_domains: string[];
        };
        UpdateSecretRequest: {
            value?: string;
            allowed_domains?: string[];
        };
        SecretResponse: {
            secret?: components["schemas"]["Secret"];
        };
        SecretsResponse: {
            secrets?: components["schemas"]["Secret"][];
        };
    };
    responses: {
        /** @description error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
    };
    parameters: {
        IdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    authConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description which login methods are enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthConfig"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description current principal */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeInfo"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    capabilities: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description registered capability factories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilityCatalog"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the user's API keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeysResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    createKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyRequest"];
            };
        };
        responses: {
            /** @description created key; `secret` is shown only once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedKey"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
        };
    };
    deleteKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listInstances: {
        parameters: {
            query?: {
                status?: components["schemas"]["InstanceStatus"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the user's instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstancesResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceSpec"];
            };
        };
        responses: {
            /** @description created instance */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            429: components["responses"]["Error"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    keepalive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description TTL bumped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    exec: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecRequest"];
            };
        };
        responses: {
            /** @description execution result (script errors return 200 with error field) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecResult"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            413: components["responses"]["Error"];
        };
    };
    files: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description directory listing or file content */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilesResult"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
        };
    };
    listExecutions: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description executions for the instance */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutionsResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listAudit: {
        parameters: {
            query?: {
                instance_id?: string;
                exec_id?: string;
                limit?: number;
                before?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description audit events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listPolicies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the user's policies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoliciesResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    createPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyRequest"];
            };
        };
        responses: {
            /** @description created policy */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    validatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ValidatePolicyRequest"];
            };
        };
        responses: {
            /** @description validation result (always 200) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
    getPolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    updatePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PolicyUpdateRequest"];
            };
        };
        responses: {
            /** @description updated policy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolicyResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    deletePolicy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    listSecrets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description vault secrets (metadata only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretsResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    createSecret: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSecretRequest"];
            };
        };
        responses: {
            /** @description created secret (metadata only) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            409: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    updateSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSecretRequest"];
            };
        };
        responses: {
            /** @description updated secret (metadata only) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecretResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    deleteSecret: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["IdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description redirect to /login */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    googleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description redirect to Google */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    googleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description redirect to / */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
        };
    };
}
type FlattenedDeepRequired<T> = {
    [K in keyof T]-?: FlattenedDeepRequired<T[K] extends unknown[] | undefined | null ? Extract<T[K], unknown[]>[number] : T[K]>;
};
type ReadonlyArray<T> = [
    Exclude<T, undefined>
] extends [
    unknown[]
] ? Readonly<Exclude<T, undefined>> : Readonly<Exclude<T, undefined>[]>;
export const instanceStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["InstanceStatus"]> = ["running", "deleted", "expired", "lost"];
export const execStatusValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ExecStatus"]> = ["ok", "error"];
export const execErrorTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["ExecErrorType"]> = ["syntax", "runtime", "policy_denied", "out_of_scope", "timeout", "step_limit", "memory_limit"];
export const decisionValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Decision"]> = ["allow", "deny"];
export const phaseValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["Phase"]> = ["", "before", "after"];
export const capabilityNameValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["CapabilityName"]> = ["fs", "net", "io"];
export const hTTPMethodValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["HTTPMethod"]> = ["GET", "HEAD", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"];
export const secretSourceValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["SecretSource"]> = ["vault", "inline"];
export const aPIErrorCodeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["APIErrorCode"]> = ["auth_failed", "bad_capability", "bad_policy", "bad_request", "bad_secret", "bad_spec", "conflict", "csrf", "forbidden", "fs_error", "internal", "method_not_allowed", "no_fs", "not_found", "not_running", "secrets_disabled", "too_large", "too_many", "unauthorized"];
export const fieldTypeValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["FieldType"]> = ["int", "bool", "string", "string_list", "string_map"];
export const authKindValues: ReadonlyArray<FlattenedDeepRequired<components>["schemas"]["AuthKind"]> = ["session", "api_key", "anonymous"];
