// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package node

import (
	"calcside/internal/instance"
)

// Injectors from wire.go:

func Build(c Config) *Node {
	registry := newRegistry(c)
	engine := newEngine(c)
	options := managerOptions(c, registry, engine)
	manager := instance.New(options)
	node := &Node{
		Registry: registry,
		Engine:   engine,
		Manager:  manager,
	}
	return node
}
