// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"calcside/cmd/calcside-worker/internal/config"
)

// Injectors from wire.go:

func initializeWorker(cfg config.WorkerConfig) (*workerApp, func(), error) {
	string2, err := provideNodeID(cfg)
	if err != nil {
		return nil, nil, err
	}
	nodeConfig := provideNodeConfig(cfg, string2)
	runtime, cleanup, err := provideRuntime(cfg, string2, nodeConfig)
	if err != nil {
		return nil, nil, err
	}
	server := provideServer(cfg, runtime)
	mainWorkerApp := &workerApp{
		Server: server,
		NodeID: string2,
	}
	return mainWorkerApp, func() {
		cleanup()
	}, nil
}
