// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apiclient

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorEnvelopeErrorKind.
const (
	BadCapability ErrorEnvelopeErrorKind = "bad_capability"
	BadSpec       ErrorEnvelopeErrorKind = "bad_spec"
	FsError       ErrorEnvelopeErrorKind = "fs_error"
	Internal      ErrorEnvelopeErrorKind = "internal"
	NoCapability  ErrorEnvelopeErrorKind = "no_capability"
	NoSuchPath    ErrorEnvelopeErrorKind = "no_such_path"
	NotFound      ErrorEnvelopeErrorKind = "not_found"
	NotOwner      ErrorEnvelopeErrorKind = "not_owner"
	NotRunning    ErrorEnvelopeErrorKind = "not_running"
	StaleEpoch    ErrorEnvelopeErrorKind = "stale_epoch"
	TooMany       ErrorEnvelopeErrorKind = "too_many"
)

// Valid indicates whether the value is a known member of the ErrorEnvelopeErrorKind enum.
func (e ErrorEnvelopeErrorKind) Valid() bool {
	switch e {
	case BadCapability:
		return true
	case BadSpec:
		return true
	case FsError:
		return true
	case Internal:
		return true
	case NoCapability:
		return true
	case NoSuchPath:
		return true
	case NotFound:
		return true
	case NotOwner:
		return true
	case NotRunning:
		return true
	case StaleEpoch:
		return true
	case TooMany:
		return true
	default:
		return false
	}
}

// ErrorEnvelope defines model for ErrorEnvelope.
type ErrorEnvelope struct {
	Error struct {
		Kind    ErrorEnvelopeErrorKind `json:"kind"`
		Message string                 `json:"message"`
	} `json:"error"`
}

// ErrorEnvelopeErrorKind defines model for ErrorEnvelope.Error.Kind.
type ErrorEnvelopeErrorKind string

// ExtTree defines model for ExtTree.
type ExtTree struct {
	// Files Slash-relative path to file contents.
	Files map[string][]byte `json:"files"`

	// Sum h1: dirhash of the source tree.
	Sum string `json:"sum"`
}

// Error defines model for Error.
type Error = ErrorEnvelope

// ExtTreeParams defines parameters for ExtTree.
type ExtTreeParams struct {
	// Path Absolute local identifier path to resolve.
	Path string `form:"path" json:"path"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ExtTree (worker → API) Fetch a local extension source tree.
	//
	// Reverse-direction call: the worker asks the API tier to read a local extension directory — workers carry no filesystem roots. The API enforces the same containment and size caps the filesystem path would, and returns the tree plus its h1 sum so the worker can cache it. Signed with the same HMAC scheme.
	//
	// Corresponds with GET /internal/v1/ext/tree (the `ExtTree` operationId).
	ExtTree(ctx context.Context, params *ExtTreeParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ExtTree (worker → API) Fetch a local extension source tree.
//
// Reverse-direction call: the worker asks the API tier to read a local extension directory — workers carry no filesystem roots. The API enforces the same containment and size caps the filesystem path would, and returns the tree plus its h1 sum so the worker can cache it. Signed with the same HMAC scheme.
//
// Corresponds with GET /internal/v1/ext/tree (the `ExtTree` operationId).
func (c *Client) ExtTree(ctx context.Context, params *ExtTreeParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewExtTreeRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewExtTreeRequest constructs an http.Request for the ExtTree method
func NewExtTreeRequest(server string, params *ExtTreeParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/ext/tree")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ExtTreeWithResponse (worker → API) Fetch a local extension source tree.
	//
	// Reverse-direction call: the worker asks the API tier to read a local extension directory — workers carry no filesystem roots. The API enforces the same containment and size caps the filesystem path would, and returns the tree plus its h1 sum so the worker can cache it. Signed with the same HMAC scheme.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /internal/v1/ext/tree (the `ExtTree` operationId).
	ExtTreeWithResponse(ctx context.Context, params *ExtTreeParams, reqEditors ...RequestEditorFn) (*ExtTreeResponse, error)
}

type ExtTreeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *ExtTree
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ExtTreeResponse) GetJSON200() *ExtTree {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ExtTreeResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ExtTreeResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ExtTreeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ExtTreeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ExtTreeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ExtTreeWithResponse (worker → API) Fetch a local extension source tree.
//
// Reverse-direction call: the worker asks the API tier to read a local extension directory — workers carry no filesystem roots. The API enforces the same containment and size caps the filesystem path would, and returns the tree plus its h1 sum so the worker can cache it. Signed with the same HMAC scheme.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /internal/v1/ext/tree (the `ExtTree` operationId).
func (c *ClientWithResponses) ExtTreeWithResponse(ctx context.Context, params *ExtTreeParams, reqEditors ...RequestEditorFn) (*ExtTreeResponse, error) {
	rsp, err := c.ExtTree(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseExtTreeResponse(rsp)
}

// ParseExtTreeResponse parses an HTTP response from a ExtTreeWithResponse call
func ParseExtTreeResponse(rsp *http.Response) (*ExtTreeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ExtTreeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ExtTree
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
