// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"calcside/internal/api"
	"calcside/internal/config"
	"calcside/internal/service/audit"
	"calcside/internal/service/catalog"
	"calcside/internal/service/iam"
	"calcside/internal/service/policy"
	"calcside/internal/service/sandbox"
	"calcside/internal/service/vault"
	"context"
	"time"
)

import (
	_ "calcside/internal/store/gormstore"
)

// Injectors from wire.go:

func initializeApp(ctx context.Context, cfg config.Config) (*application, func(), error) {
	store, cleanup, err := provideStore(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	v := _wireValue
	service := iam.New(store, v)
	cipher, err := provideCipher(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	vaultService := vault.New(store, cipher)
	policyService := policy.New(store)
	auditService := audit.New(store)
	serverLimits := provideLimits(cfg)
	nodeConfig := provideNodeConfig(cfg, serverLimits)
	node, cleanup2 := provideNode(nodeConfig)
	registry := node.Registry
	catalogService := catalog.New(registry)
	runtime, cleanup3, err := provideRuntime(cfg, store, nodeConfig, node)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	recorder, cleanup4 := provideRecorder(store)
	v2, err := provideGlobalPolicies(cfg)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	options, err := provideSandboxOptions(ctx, cfg, store, runtime, vaultService, recorder, registry, serverLimits, v2)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	sandboxService := sandbox.New(options)
	authService := provideAuth(cfg, store)
	basicLogin, err := provideBasic(ctx, cfg, authService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	fs := provideWeb()
	user, err := provideAnonymous(ctx, cfg, store)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	artifactPreviews, cleanup5, err := provideArtifacts(cfg, sandboxService)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	deps := api.Deps{
		IAM:       service,
		Vault:     vaultService,
		Policy:    policyService,
		Audit:     auditService,
		Catalog:   catalogService,
		Sandbox:   sandboxService,
		Auth:      authService,
		Basic:     basicLogin,
		Web:       fs,
		Anonymous: user,
		Previews:  artifactPreviews,
	}
	googleFlow, err := provideGoogle(ctx, cfg)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	server := provideServer(cfg, deps, googleFlow)
	mainApplication := &application{
		Server:  server,
		Sandbox: sandboxService,
	}
	return mainApplication, func() {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireValue = time.Now
)
